### PR TITLE
Improved hand model

### PR DESCRIPTION
**Pull request by trhermans**
I've cherry-picked my commits to setup the URDF of the right hand for use in simulation.

I have primarily tested this using Klamp't, but it should help for working in Gazebo as well.

### CODE REVIEW

**Comment by felixduvallet** [comment]
Thanks for the PR, it'll likely be a few days before I can merge everything but it's on my list!

**Comment by felixduvallet** [comment]
Thanks again for the inertial parameters. I copied them into the xacro files for both hands and created #9 which IMO supersedes #5 . Are you okay if I close this PR?

Note that I was not able to get the simulation to run successfully, the hand starts fine but explodes immediately. My gazebo-foo is pretty low, perhaps you can figure out a solution (if so, please let me know!).

**Comment by trhermans** [comment]
That looks good to me.

We're working on improving the parameters for gazebo and should hopefully
have something working in the next week or so.

I'll let you know when we get it.

-Tucker

**Comment by felixduvallet** [comment]
Thanks, that would be great.
I don't use Gazebo personally, but getting that working would be a great contribution to the community.

**Pull request closed without merging**
